/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaCliente.java
 *
 * Created on 13/10/2011, 15:07:37
 */

package gui.janelas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import network.ClientHandler;
import org.xsocket.connection.INonBlockingConnection;
import org.xsocket.connection.NonBlockingConnection;

/**
 *
 * @author dolalima
 */
public class JanelaCliente extends JFrame {
    
    private INonBlockingConnection bc;

    /** Creates new form JanelaCliente */
    public JanelaCliente() {
        initComponents();
        
        try {
            bc = new NonBlockingConnection("localhost", 8090, new ClientHandler());
        } catch(IOException ioException){
            Logger.getLogger(JanelaCliente.class.getName()).log(Level.SEVERE, null, ioException);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    //@Override
    public void sendDataTo(String destinatario, String message) throws IOException {
        bc.write(getName() + "~~" + destinatario + "~~" + message + "\n");
    }

    //@Override
    public void sendDataToAll(String message) throws IOException {
        bc.write(getName() + "~~" + message + "\n");
    }

    //@Override
    public void onClose() throws IOException {
        Thread t = new Thread() {
            @Override
            public void start() {
                try {
                    sendDataToAll("Desconectou-se");
                } catch(IOException ex){ }
            }
        };
        t.start();
        try {
            Thread.sleep(100);
        } catch(InterruptedException ex){ }
        bc.close();
    }
    

}
