/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaServidor.java
 *
 * Created on 13/10/2011, 16:15:22
 */
package gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import network.ServerHandler;
import org.xsocket.connection.IServer;
import org.xsocket.connection.Server;

/**
 *
 * @author dolalima
 */
public class JanelaServidor extends JanelaPrincipal {

    private IServer srv;
    private ServerHandler handler;

    /** Creates new form JanelaServidor */
    public JanelaServidor() {
        initComponents();
        this.setJogador("Servidor");

        try {
            handler = new ServerHandler();
            srv = new Server(8090, handler);
            this.displayMessage("Esperando Conexão...");
            srv.start();
        } catch (IOException ioException) {
            Logger.getLogger(JanelaCliente.class.getName()).log(Level.SEVERE, null, ioException);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void sendDataTo(String destinatario, String message) throws IOException {
        handler.sendMessageTo(getName(), destinatario, message);
    }

    @Override
    public void sendDataToAll(String message) throws IOException {
        handler.sendMessageToAll(getName(), message);
    }

    @Override
    public void onClose() throws IOException {
        try {
            sendDataToAll("Saiu");
            srv.close();
        } catch (IOException ex) {
            Logger.getLogger(JanelaServidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
